# Generated by Django 4.1.2 on 2023-05-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='rating',
            new_name='num_rating',
        ),
    ]
