# Generated by Django 4.1.2 on 2023-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_rename_rating_media_num_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
